steam:
  api:
    key: xxxxx # 务必使用你的真实 Key
    # baseUrl: https://api.steampowered.com # 默认已经是这个

# application.yml
spring:
  ai:
    dashscope:
      api-key: sk-xxxxxxxxxx
      chat:
        options:
          model: qwen-plus

search-api:
  base-url: https://www.searchapi.io/api/v1/search?engine=google
  api-key: xxxxxxxxxx