-- =====================================================================
-- V1: Initial schema for Raymi dev H2 file database
-- 与 @Entity 元数据保持严格一致,供 spring.jpa.hibernate.ddl-auto=validate 校验
--
-- 命名约定(放弃双引号大小写锁定):
--   * schema / table / column 全部不使用双引号,让 H2 默认 DATABASE_TO_UPPER=TRUE
--     把无引号 identifier 一律转大写(STEAM / OWNED_GAME / STEAMID / APP_ID ...)。
--   * Entity 端 JPA 默认也是大写比对,所以 metadata 查询时大小写一致。
--   * 不要在列名或表名上使用双引号,会让大小写被字面锁死,与 Hibernate 默认大写比对冲突。
--
-- 两个 schema (STEAM / SYSTEM) 由 spring.flyway.schemas=STEAM,SYSTEM 配置自动创建,
-- 本脚本不重复 DDL(否则 H2 抛 90078 Schema already exists)。
-- =====================================================================

-- ---------------------------------------------------------------------
-- STEAM.owned_game
-- 实体: com.rikka.raymispring.model.entity.OwnedSteamGameEntity
-- 主键: (steamid, app_id)
-- ---------------------------------------------------------------------
CREATE TABLE steam.owned_game (
    app_id                       INTEGER       NOT NULL,
    steamid                      VARCHAR(64)   NOT NULL,
    created_at                   TIMESTAMP(6),
    has_community_visible_stats  BOOLEAN,
    img_icon_url                 VARCHAR(255),
    name                         VARCHAR(255),
    playtime_deck_forever        INTEGER,
    playtime_forever             INTEGER,
    playtime_linux_forever       INTEGER,
    playtime_mac_forever         INTEGER,
    playtime_windows_forever     INTEGER,
    rtime_last_played            BIGINT,
    updated_at                   TIMESTAMP(6),
    PRIMARY KEY (app_id, steamid)
);

-- ---------------------------------------------------------------------
-- STEAM.owned_game_content_descriptor
-- @ElementCollection 副表,联合外键到 owned_game
-- ---------------------------------------------------------------------
CREATE TABLE steam.owned_game_content_descriptor (
    app_id         INTEGER       NOT NULL,
    steamid        VARCHAR(64)   NOT NULL,
    descriptor_id  INTEGER,
    CONSTRAINT fk_owned_game_content_descriptor_owned_game
        FOREIGN KEY (app_id, steamid)
        REFERENCES steam.owned_game (app_id, steamid)
);

-- ---------------------------------------------------------------------
-- STEAM.player_achievements
-- 实体: com.rikka.raymispring.model.entity.PlayerAchievementsEntity
-- 主键: (steamid, app_id, api_name)
-- ---------------------------------------------------------------------
CREATE TABLE steam.player_achievements (
    api_name     VARCHAR(255) NOT NULL,
    app_id       INTEGER      NOT NULL,
    steamid      VARCHAR(64)  NOT NULL,
    achieved     INTEGER,
    created_at   TIMESTAMP(6),
    description  VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    unlock_date  TIMESTAMP(6),
    unlock_time  BIGINT,
    updated_at   TIMESTAMP(6),
    PRIMARY KEY (api_name, app_id, steamid)
);

-- ---------------------------------------------------------------------
-- SYSTEM.exception_log
-- 实体: com.rikka.raymispring.model.entity.ExceptionLogEntity
-- 主键: 自增 ID
-- ---------------------------------------------------------------------
CREATE TABLE system.exception_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at        TIMESTAMP(6),
    data_source       VARCHAR(64)   NOT NULL,
    error_code        VARCHAR(5)    NOT NULL,
    error_code_desc   VARCHAR(128)  NOT NULL,
    error_message     VARCHAR(1024) NOT NULL,
    remark            VARCHAR(512),
    source_data_json  TEXT,
    PRIMARY KEY (id)
);
